name: pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  FILE_PATH_WEB_BUILD: ./apps/web/dist/build/.next
  FILE_PATH_UI_BUILD: ./packages/ui/dist/storybook

  CACHE_PATHS_BUILD: |
    ./apps/web/dist/build/.next
    ./packages/ui/dist/storybook
  CACHE_KEY_BUILD: build-${{ github.sha }}-${{ github.ref_type }}
  CACHE_RESTORE_KEYS: build-
  
jobs:
  compile:
    name: ğŸ¥‰ Compile and Lint
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: ğŸ’» TypeScript Compiler
        run: yarn --filter="...[HEAD^] type-check"
      
      - name: ğŸŸ© Lint 
        run: yarn --filter="...[HEAD^] lint"

      - name: âš¡ Turbo Cache
        id: turbo-cache
        uses: actions/cache@v4.0.2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

  build:
    name: ğŸ¥ˆ Build
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: ğŸ—ï¸ Build
        run: |
          yarn build
          yarn storybook-build

      - name: âš¡ Turbo Cache
        id: turbo-cache
        uses: actions/cache@v4.0.2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: âš¡ Build Cache
        id: cache_build
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}
          restore-keys: ${{ env.CACHE_RESTORE_KEYS }}

  test:
    name: ğŸ¥‡ Test
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: ğŸ“£ Test
        run: yarn test-coverage --filter="...[HEAD^]"

  quality-gate:
    name: ğŸš€ Quality Gate
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan ğŸ‘
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}